#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y update
sudo apt-get -y install haproxy

sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen balancer\n\tbind :80\n\tbalance roundrobin\n\tserver 103446-web-01 100.26.53.67:80 check\n\tserver 103446-web-02 100.24.244.107:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
