#!/usr/bin/env bash
#load-balancing server
	

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get update -y
sudo apt-get install -y haproxy=2.4.\*
	

sudo echo \
	"
frontend localnodes
	bind *:80
	mode http
	default_backend nodes
backend nodes
	mode http
	balance roundrobin
	server 103446-web-01 100.26.53.67
	server 103446-web-02 100.24.244.107" >> /etc/haproxy/haproxy.cfg
	

sudo service haproxy restart
