#!/usr/bin/env bash
#this is a while and if statement
bash script is displaying "Best School" 10 times
i=1
while [ $i -lt 11 ];
do
	if [ $i == 10 ];
	then
		echo "Hi"
	fi
		echo "Best School"
		((i++))
done
