#!/usr/bin/env bash
#loop with 4th and 8th condition
x=1
while [ $x -lt 11 ];
do
	if [ $x == 4 ];
	then
		echo "bad luck"
	elif [ $x == 8 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((x++))
done
