#!/usr/bin/env bash
#nested while look
# 	displays hours
#	displays minutes
outer=0
while [ $outer -le 12 ]; do
	echo "Hour: $outer"
	inner=1
	while [ $inner -le 59 ]; do
		echo "$inner"
		(( inner++ ))
	done
	(( outer++ ))
done
